name: parallel build

on:
  push:
    branches:
      - main

jobs:
  Cart-run:
    if: github.workflow == 'parallel build'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            command: npm run test-addToCart

      - name: Cypress report test for cart
        uses: actions/upload-artifact@v4
        with:
          name: HTML Report - Cart 1
          path: cypress/reports/html

  Reg-run:
    if: github.workflow == 'parallel build'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # Install npm dependencies, cache them correctly
        # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            command: npm run test-flow

      - name: Cypress report test for reg
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: HTML Report - Reg 1
          path: cypress/reports/html

      - name: Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Test Automation Report https://github.com/daiyanrafi/cypress-e2e-with-CI-CD/actions/runs/${{github.run_id}}'
          SLACK_TITLE: Cypress E2E Test
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
