name: parallel build

on:
  push:
    branches:
      - main

jobs:
  Cart-run:
    if: github.workflow == 'parallel build'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            command: npm run test-addToCart

      - name: Cypress report test for cart
        uses: actions/upload-artifact@v4
        with:
          name: HTML Report
          path: cypress/reports/html

  Reg-run:
    if: github.workflow == 'parallel build'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # Install npm dependencies, cache them correctly
        # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            command: npm run test-flow

      - name: Cypress report test for reg
        uses: actions/upload-artifact@v4
        with:
          name: HTML Report
          path: cypress/reports/html
